mirrors:
  local-cache:
    fetch:
      url: file:///data/prod/jedi/spack-stack/cache
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
    push:
      url: file:///data/prod/jedi/spack-stack/cache
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
