spack:
  concretization: separately
  view: false
  include:
  - config.yaml
  - packages.yaml
  - modules.yaml
  - ${SPACK_STACK_DIR}/configs/repos/repos.yaml
  - site.yaml

 specs:
      - cmake
      - zlib
      - hdf5
      - parallel-netcdf
      - netcdf-c
      - netcdf-fortran
      - nccmp
      - libjpeg
      - libpng
      - jasper
      - esmf
      - fms
      - fms-jcsda
      - udunits
      - bacio
      - sigio
      - sfcio
      - gfsio
      - w3nco
      - w3emc
      - sp
      - ip
      - ip2
      - landsfcutil
      - nemsio
      - nemsiogfs
      - g2
      - g2c
      - g2tmpl
      - crtm
      - upp
      - wrf-io
      - wgrib2
      - prod-util
      - grib-util
      - py-h5py
      - jedi-cmake
      - boost
      - gsl-lite
      - eigen
      - ecbuild
      - eckit
      - fckit
      - atlas
      - git
      - git-lfs
      - py-numpy
      - py-pybind11
      - py-netcdf4
      - py-pycodestyle
      - diffutils
      - findutils
