  # Set package and module installation directories
  config:
    install_hash_length: 3
    install_tree:
      root: install
      projections:
        all:  "${COMPILERNAME}/${COMPILERVER}/${PACKAGE}/${VERSION}-${HASH}"
    module_roots:
      lmod: install/modulefiles
