  # Set package and module installation directories
  config:
    install_tree:
      root: install
      projections:
        all: ${PACKAGE}-${VERSION}
    module_roots:
      lmod: install/modulefiles
