spack:
  concretizer:
    unify: when_possible

  view: false
  include: []

  definitions:
  - compilers: [populated-by-create-env]
  - packages:
      - global-workflow-env@unified-dev
      #- gsi-env@unified-dev
      - jedi-ewok-env@unified-dev
      - jedi-fv3-env@unified-dev
      - jedi-tools-env@unified-dev
      - jedi-ufs-env@unified-dev
      - jedi-um-env@unified-dev
      #- nceplibs-env@unified-dev
      - soca-env@unified-dev
      - ufs-srw-app-env@unified-dev
      #- ufs-utils-env@unified-dev
      - ufs-weather-model-env~debug@unified-dev
      - ufs-weather-model-env+debug@unified-dev
      #- upp-env@unified-dev
      #- ww3-env@unified-dev

  specs:
    - matrix:
      - [$packages]
      - [$compilers]
      exclude:
        - jedi-tools-env%intel
