spack:
  concretizer:
    unify: when_possible

  config:
    install_tree:
      root: $env/install
  modules:
    default:
      roots:
        lmod: $env/install/modulefiles
        tcl: $env/install/modulefiles

  view: false
  include: []

  specs:
  - awscli
  - bacio
  - boost
  - bufr
  - cairo
  - cdo
  - cfitsio
  - cmake
  - crtm
  - curl
  - ecflow
  - eigen
  - esmf
  - fms
  - g2
  - g2c
  - g2tmpl
  - gdal
  - geos
  - gfsio
  - git
  - grib-util
  - gsl
  - hdf5
  - imagemagick
  - ip
  - ip2
  - jasper
  - landsfcutil
  - libgeotiff
  - libiconv
  - libjpeg-turbo
  - libpng
  - libtiff
  - libxml2
  - libxrender
  - madis
  - mapl
  - mbedtls
  - met
  - metis
  - metplus
  - nco
  - ncivew
  - nemsio
  - nemsiogfs
  - netcdf-c +fismahigh
  - netcdf-fortran
  - perl
  - pigz
  - parallelio
  - pixman
  - proj
  - python
  - readline
  - rsync
  - scotch
  - sfcio
  - sigio
  - sp
  - subversion
  - udunits
  - upp
  - w3emc
  - w3enco
  - wgrib2
  - wrf-io

  packages:
    all:
      prefer: 'intel@19.1.3.304'
    mpi:
      require: cray-mpich
    fftw-api:
      require: fftw
    blas:
      require: openblas
    lapack:
      require: openblas
    jpeg:
      require: libjpeg-turbo
