modules:
  default:
    enable::
    - lmod
    lmod:
      whitelist:
      # List of packages for which we need modules that are blacklisted by default
      - openmpi
      - mpich
      texlive:
        environment:
          prepend-path:
            PATH: '/usr/local/texlive/2022/bin/universal-darwin'
