  boost:
    require::
    - '@1.84 ~atomic +chrono +date_time +exception +filesystem ~graph ~iostreams
      ~locale ~log ~math ~mpi ~numpy +pic +program_options +python ~random +regex
      +serialization ~signals +system +test +thread +timer ~wave visibility=hidden cxxstd=17'
  cdo:
    require: ['grib2=none']
  curl:
    require: ['~nghttp2']   # avoid nghttp2 dependency

  ecmwf-atlas:
    'require:':
    - +fckit ~trans ~fftw   # disabling trans and fftw to minimize dependencies; older version because newer eckit doesn't build with intel@19
  ectrans:
    require:: ['+fftw']
  git-lfs:
    require: ['%gcc']
  icu4c:
    require: ['%gcc']
  mapl:
    require:
    - ~pflogger ~fargparse ~extdata2g #   minimize dependencies
  netcdf-c:
    require:: +mpi ~parallel-netcdf ~dap ~blosc ~szip build_system=autotools # disabling dap prevents network access; disabling blosc and szip reduces dependencies
  py-pandas:
    'require:': ~excel #   minimize dependencies
  subversion:
    require:
    - ~serf +pic #   avoid serf dependency
  zlib-ng:
    require: ['+compat ~new_strategies']
  crtm:
    require: ['@2.4.0.1', '+fix']
  scotch:
    require:: 
    - '@7.0.7'
    - '+mpi'
    - '+metis'
    - '~shared'
    - '~threads'
    - '~mpi_thread'
    - '+noarch'
    - '+esmumps'
    - 'build_system=cmake'
