compilers:
- compiler:
    spec: intel@19.1.3.304
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    modules:
    - PrgEnv-intel/8.3.3
    - craype/2.7.13
    - intel/19.1.3.304
    environment:
      set:
        # OpenSUSE on WCOSS2 machines sets CONFIG_SITE so 
        # Automake-based builds are installed in lib64 
        # which confuses some packages.
        CONFIG_SITE: ''
        PATH: '/pe/intel/compilers_and_libraries_2020.4.304/linux/bin/intel64:/pe/intel/compilers_and_libraries_2020.4.304/linux/bin:/pe/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin:/pe/intel/debugger_2020/gdb/intel64/bin:/opt/cray/pe/craype/2.7.13/bin:/opt/cray/libfabric/1.11.0.0./bin:/usr/bin:/bin'
    extra_rpaths: []
- compiler:
    spec: gcc@11.2.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    modules:
    - PrgEnv-gnu/8.3.3
    - craype/2.7.13
    - gcc/11.2.0
    environment:
      set:
        # OpenSUSE on WCOSS2 machines sets CONFIG_SITE so 
        # Automake-based builds are installed in lib64 
        # which confuses some packages.
        CONFIG_SITE: ''
        PATH: '/opt/cray/pe/gcc/11.2.0/bin:/opt/cray/pe/craype/2.7.13/bin:/opt/cray/libfabric/1.11.0.0./bin:/usr/bin:/bin'
    extra_rpaths: []
