compilers:
- compiler:
    spec: intel@19.1.3.304
    paths:
      cc: /opt/cray/pe/craype/2.7.13/bin/cc
      cxx: /opt/cray/pe/craype/2.7.13/bin/CC
      f77: /opt/cray/pe/craype/2.7.13/bin/ftn
      fc: /opt/cray/pe/craype/2.7.13/bin/ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - craype-x86-rome
    - libfabric
    - craype-network-ofi
    - envvar
    - PrgEnv-intel
    - intel/19.1.3.304
    - craype/2.7.13
    - cray-mpich/8.1.9
    environment:
      set:
        # OpenSUSE on WCOSS2 machines sets CONFIG_SITE so 
        # Automake-based builds are installed in lib64 
        # which confuses some packages.
        CONFIG_SITE: ''
    extra_rpaths: []
- compiler:
    spec: cce@14.0.3
    paths:
      cc: /opt/cray/pe/craype/2.7.13/bin/cc
      cxx: /opt/cray/pe/craype/2.7.13/bin/CC
      f77: /opt/cray/pe/craype/2.7.13/bin/ftn
      fc: /opt/cray/pe/craype/2.7.13/bin/ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-cray/8.3.3
    - cce/14.0.3
    - craype/2.7.13
    - cray-mpich/8.1.9
    environment:
      set:
        # OpenSUSE on WCOSS2 machines sets CONFIG_SITE so 
        # Automake-based builds are installed in lib64 
        # which confuses some packages.
        CONFIG_SITE: ''
    extra_rpaths: []
