  packages:
    all:
      compiler:: [intel@19.1.3.304,cce@14.0.3]
      providers:
        mpi:: [cray-mpich@8.1.9]
    cray-mpich:
      externals:
      - spec: cray-mpich@8.1.9~wrappers
        modules:
        - libfabric
        - craype-network-ofi
        - cray-mpich/8.1.9
    openssl:
      buildable: false
      externals:
      - spec: openssl@1.1.1d
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.34
        prefix: /usr
    diffutils:
      buildable: false
      externals:
      - spec: diffutils@3.6
        prefix: /usr
    pkgconfig:
      buildable: false
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.18
        prefix: /usr
    openssh:
      buildable: false
      externals:
      - spec: openssh@8.4p1
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.29.2
        prefix: /usr
    wget:
      buildable: false
      externals:
      - spec: wget@1.20.3
        prefix: /usr
    cmake:
      buildable: false
      externals:
      - spec: cmake@3.20.2
        prefix: /apps/spack/cmake/3.20.2/intel/19.1.3.304/utnbptm3hrf7gppztidueu4jogfgemut
    git:
      buildable: false
      externals:
      - spec: git@2.35.3
        prefix: /usr
      externals:
      - spec: git@2.29.0
        modules: [git/2.29.0]
    git-lfs:
      buildable: false
      externals:
      - spec: git-lfs@2.11.0
        modules: [git-lfs/2.11.0]
    python:
      buildable: false
      externals:
      - spec: python@3.8.6+bz2+ctypes+dbm+lzma~nis+pyexpat+pythoncmd+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
        prefix: /apps/spack/python/3.8.6/intel/19.1.3.304/pjn2nzkjvqgmjw4hmyz43v5x4jbxjzpk
    perl:
      buildable: false
      externals:
      - spec: perl@5.26.1~cpanm+shared+threads
        prefix: /usr
