packages:
  # Use x86_64 for all packages
  all:
    require: ['target=x86_64']
  #
  ### Compilers
  #
  c:
    prefer: ['intel-oneapi-compilers']
  cxx:
    prefer: ['intel-oneapi-compilers']
  fortran:
    require: ['intel-oneapi-compilers']
  intel-oneapi-compilers:
    buildable: false
    externals:
    - spec: intel-oneapi-compilers@2026.1.0
      prefix: /opt/intel/oneapi
      extra_attributes:
        compilers:
          c: /opt/intel/oneapi/compiler/2026.1/bin/icx
          cxx: /opt/intel/oneapi/compiler/2026.1/bin/icpx
          fortran: /opt/intel/oneapi/compiler/2026.1/bin/ifx
  gcc:
    buildable: false
    externals:
      - spec: gcc@14.2.0 languages:='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc-14
            cxx: /usr/bin/g++-14
            fortran: /usr/bin/gfortran-14
  gcc-runtime:
    require: '%gcc@14.2.0'
  #
  ### Provider settings & externals
  #
  mpi:
    buildable: false
    require: 'intel-oneapi-mpi'
  intel-oneapi-mpi:
    externals:
    - spec: intel-oneapi-mpi@2021.18~external-libfabric+ilp64
      prefix: /opt/intel/oneapi/
  blas:
    require:: ['openblas']
  lapack:
    require:: ['openblas']
  fftw-api:
    require:: ['fftw']
  #
  ### Individual package settings
  #
  nco:
   require:: ['@:'] # ignore common/packages_oneapi.yaml setting
