modules:
  default:
    enable::
    - tcl
    - lmod
    tcl:
      whitelist:
      # List of packages for which we need modules that are blacklisted by default
      - openmpi
      - mpich
    lmod:
      whitelist:
      # List of packages for which we need modules that are blacklisted by default
      - openmpi
      - mpich
