spack:
  concretizer:
    unify: when_possible

  config:
    install_tree:
      root: $env/install
    deprecated: true

  view: false

  include: []

  specs:
  - bacio
  - bufr
  - cdo
#  - cfitsio
  - crtm@=3.1.2
  - ecmwf-atlas
  - esmf@8.8.0
  - fms
  - g2
  - g2c
  - g2tmpl
#  - gdal
#  - geos
  - gempak
  - gfsio
  - gftl-shared
  - grib-util
  - gsi-ncdiag
  - gsl
#  - gsl-lite
  - hdf5
  - ip
  - jasper
  - landsfcutil
  - libgeotiff
  - libjpeg-turbo
  - libpng
  - libtiff
  - libxml2
  - madis
  - mapl@2.53.4 ^esmf@8.8.0
  - met
  - metis
  - metplus
#  - nccmp
  - nco
#  - ncview
  - nemsio
  - netcdf-c
  - netcdf-fortran
  - parallelio
  - python
#  - qhull
  - scotch
  - sfcio
  - sigio
  - sp
  - udunits
  - upp ^crtm@=2.4.0.1
  - w3emc
  - w3nco
  - wgrib2
  - wrf-io
  - xml-fortran
