packages:
  all:
    compiler: [intel@19.1.3.304]    
  python:
    externals:
    - spec: python@3.8.6+bz2+ctypes+dbm+lzma~nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      modules:
      - python/3.8.6
    buildable: False
  openssl:
    externals:
    - spec: openssl@1.1.1d
      prefix: /usr
    buildable: False
  cmake:
    externals:
    - spec: cmake@3.20.2
      prefix: /apps/spack/cmake/3.20.2/intel/19.1.3.304/utnbptm3hrf7gppztidueu4jogfgemut
    buildable: False
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
    buildable: False
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
    buildable: False
  perl:
    externals:
    - spec: perl@5.32.0+cpanm+shared+threads
      modules:
      - perl/5.32.0
    buildable: False
