compilers:
- compiler:
    spec: intel@18.0.5.274
    paths:
      cc: /apps/intel/parallel_studio_xe_2018.4.057/compilers_and_libraries_2018/linux/bin/intel64/icc
      cxx: /apps/intel/parallel_studio_xe_2018.4.057/compilers_and_libraries_2018/linux/bin/intel64/icpc
      f77: /apps/intel/parallel_studio_xe_2018.4.057/compilers_and_libraries_2018/linux/bin/intel64/ifort
      fc: /apps/intel/parallel_studio_xe_2018.4.057/compilers_and_libraries_2018/linux/bin/intel64/ifort
    flags: {}
    operating_system: centos7
    target: any
    modules:
    - intel/18.0.5.274
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@19.0.5.281
    paths:
      cc: /apps/intel/parallel_studio_xe_2019.5.075/compilers_and_libraries_2019/linux/bin/intel64/icc
      cxx: /apps/intel/parallel_studio_xe_2019.5.075/compilers_and_libraries_2019/linux/bin/intel64/icpc
      f77: /apps/intel/parallel_studio_xe_2019.5.075/compilers_and_libraries_2019/linux/bin/intel64/ifort
      fc: /apps/intel/parallel_studio_xe_2019.5.075/compilers_and_libraries_2019/linux/bin/intel64/ifort
    flags: {}
    operating_system: centos7
    target: any
    modules:
    - intel/19.0.5.281
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@2020
    paths:
      cc: /apps/intel/parallel_studio_xe_2020.0.088/compilers_and_libraries_2020/linux/bin/intel64/icc
      cxx: /apps/intel/parallel_studio_xe_2020.0.088/compilers_and_libraries_2020/linux/bin/intel64/icpc
      f77: /apps/intel/parallel_studio_xe_2020.0.088/compilers_and_libraries_2020/linux/bin/intel64/ifort
      fc: /apps/intel/parallel_studio_xe_2020.0.088/compilers_and_libraries_2020/linux/bin/intel64/ifort
    flags: {}
    operating_system: centos7
    target: any
    modules:
    - intel/2020
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@2020.2
    paths:
      cc: /apps/intel/parallel_studio_xe_2020.2.108/compilers_and_libraries_2020/linux/bin/intel64/icc
      cxx: /apps/intel/parallel_studio_xe_2020.2.108/compilers_and_libraries_2020/linux/bin/intel64/icpc
      f77: /apps/intel/parallel_studio_xe_2020.2.108/compilers_and_libraries_2020/linux/bin/intel64/ifort
      fc: /apps/intel/parallel_studio_xe_2020.2.108/compilers_and_libraries_2020/linux/bin/intel64/ifort
    flags: {}
    operating_system: centos7
    target: any
    modules:
    - intel/2020.2
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@2021.3.0
    paths:
      cc: /apps/oneapi/compiler/2021.3.0/linux/bin/intel64/icc
      cxx: /apps/oneapi/compiler/2021.3.0/linux/bin/intel64/icpc
      f77: /apps/oneapi/compiler/2021.3.0/linux/bin/intel64/ifort
      fc: /apps/oneapi/compiler/2021.3.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: centos7
    target: any
    modules:
    - intel/2021.3.0
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@9.2.0
    paths:
      cc: /apps/gnu/gcc-9.2.0/bin/gcc
      cxx: /apps/gnu/gcc-9.2.0/bin/g++
      f77: /apps/gnu/gcc-9.2.0/bin/gfortran
      fc:  /apps/gnu/gcc-9.2.0/bin/gfortran
    flags: {}
    operating_system: centos7
    target: any
    modules:
    - gnu/9.2.0
    environment: {}
    extra_rpaths: []