compilers::

  #- compiler:
  #    spec: intel@18.0.5.274
  #    paths:
  #      cc: /apps/intel/parallel_studio_xe_2018.4.057/compilers_and_libraries_2018/linux/bin/intel64/icc
  #      cxx: /apps/intel/parallel_studio_xe_2018.4.057/compilers_and_libraries_2018/linux/bin/intel64/icpc
  #      f77: /apps/intel/parallel_studio_xe_2018.4.057/compilers_and_libraries_2018/linux/bin/intel64/ifort
  #      fc: /apps/intel/parallel_studio_xe_2018.4.057/compilers_and_libraries_2018/linux/bin/intel64/ifort
  #    flags: {}
  #    operating_system: centos7
  #    target: any
  #    modules:
  #    - intel/18.0.5.274
  #    environment:
  #      prepend_path:
  #        LD_LIBRARY_PATH: '/apps/gnu/gcc-9.2.0/lib64'
  #      set:
  #        CXXFLAGS: '-std=c++14 -gxx-name=/apps/gnu/gcc-9.2.0/bin/g++ -Wl,-rpath,/apps/gnu/gcc-9.2.0/lib64'
  #        LDFLAGS: '-std=c++14 -gxx-name=/apps/gnu/gcc-9.2.0/bin/g++ -Wl,-rpath,/apps/gnu/gcc-9.2.0/lib64'
  #    extra_rpaths: []

  - compiler:
      spec: intel@2021.3.0
      paths:
        cc: /apps/oneapi/compiler/2021.3.0/linux/bin/intel64/icc
        cxx: /apps/oneapi/compiler/2021.3.0/linux/bin/intel64/icpc
        f77: /apps/oneapi/compiler/2021.3.0/linux/bin/intel64/ifort
        fc: /apps/oneapi/compiler/2021.3.0/linux/bin/intel64/ifort
      flags: {}
      operating_system: centos7
      target: x86_64
      modules:
      - intel/2021.3.0
      environment:
        prepend_path:
          LD_LIBRARY_PATH: '/apps/gnu/gcc-9.2.0/lib64'
        set:
          CXXFLAGS: '-std=c++14 -gxx-name=/apps/gnu/gcc-9.2.0/bin/g++ -Wl,-rpath,/apps/gnu/gcc-9.2.0/lib64'
          LDFLAGS: '-std=c++14 -gxx-name=/apps/gnu/gcc-9.2.0/bin/g++ -Wl,-rpath,/apps/gnu/gcc-9.2.0/lib64'
      extra_rpaths: []
          #setenv("ACL_BOARD_VENDOR_PATH","/opt/Intel/OpenCLFPGA/oneAPI/Boards")
          #setenv("CMPLR_ROOT","/apps/oneapi/compiler/2021.3.0")
          #setenv("CPATH","/apps/oneapi/compiler/2021.3.0/linux/include")
          #setenv("FPGA_VARS_ARGS","")
          #setenv("FPGA_VARS_DIR","/apps/oneapi/compiler/2021.3.0/linux/lib/oclfpga")
          #setenv("INTELFPGAOCLSDKROOT","/apps/oneapi/compiler/2021.3.0/linux/lib/oclfpga")
          #prepend_path("LD_LIBRARY_PATH","/apps/oneapi/compiler/2021.3.0/linux/compiler/lib/intel64_lin")
          #prepend_path("LD_LIBRARY_PATH","/apps/oneapi/compiler/2021.3.0/linux/lib/oclfpga/linux64/lib")
          #prepend_path("LD_LIBRARY_PATH","/apps/oneapi/compiler/2021.3.0/linux/lib/oclfpga/host/linux64/lib")
          #prepend_path("LD_LIBRARY_PATH","/apps/oneapi/compiler/2021.3.0/linux/lib/emu")
          #prepend_path("LD_LIBRARY_PATH","/apps/oneapi/compiler/2021.3.0/linux/lib/x64")
          #prepend_path("LD_LIBRARY_PATH","/apps/oneapi/compiler/2021.3.0/linux/lib")
          #setenv("LIBRARY_PATH","/apps/oneapi/compiler/2021.3.0/linux/compiler/lib/intel64_lin:/apps/oneapi/compiler/2021.3.0/linux/lib")
          #prepend_path("MANPATH","/apps/oneapi/compiler/2021.3.0/documentation/en/man/common")
          #setenv("OCL_ICD_FILENAMES","libintelocl_emu.so:libalteracl.so:/apps/oneapi/compiler/2021.3.0/linux/lib/x64/libintelocl.so")
          #prepend_path("PATH","/apps/oneapi/compiler/2021.3.0/linux/bin")
          #prepend_path("PATH","/apps/oneapi/compiler/2021.3.0/linux/bin/intel64")
          #prepend_path("PATH","/apps/oneapi/compiler/2021.3.0/linux/lib/oclfpga/bin")
          #prepend_path("PATH","/apps/oneapi/compiler/2021.3.0/linux/lib/oclfpga/llvm/aocl-bin")
          #setenv("CPATH","/apps/oneapi/mkl/2021.3.0/include")
          #prepend_path("LD_LIBRARY_PATH","/apps/oneapi/mkl/2021.3.0/lib/intel64")
          #setenv("LIBRARY_PATH","/apps/oneapi/mkl/2021.3.0/lib/intel64")
          #setenv("MKLROOT","/apps/oneapi/mkl/2021.3.0")
          #setenv("NLSPATH","/apps/oneapi/mkl/2021.3.0/lib/intel64/locale/%l_%t/%N")
          #prepend_path("PATH","/apps/oneapi/mkl/2021.3.0/bin/intel64")
          #setenv("PKG_CONFIG_PATH","/apps/oneapi/mkl/2021.3.0/tools/pkgconfig")
          #family("compiler")
          #append_path("MODULEPATH","/apps/modules/modulefamilies/intel")

  - compiler:
      spec: gcc@4.8
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: centos7
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
