packages:

  mpi:
    buildable: False

  intel-mpi:
    buildable: False
    externals:
    #- spec: intel-mpi@2018.0.4
    #  modules:
    #  - impi/2018.0.4
    - spec: intel-oneapi-mpi@2021.3.0
      modules:
      - impi/2021.3.0

  python:
    buildable: False
    externals:
    - spec: python@3.7.10
      modules:
      - intelpython/2021.3.0

  openssl:
    externals:
    - spec: openssl@1.0.2r
      prefix: /apps/intel/intelpython3
    - spec: openssl@1.0.2k-fips
      prefix: /usr

  perl:
    externals:
    - spec: perl@5.16.3~cpanm+shared+threads
      prefix: /usr

  m4:
    externals:
    - spec: m4@1.4.16
      prefix: /usr

  cmake:
    buildable: False
    externals:
    - spec: cmake@3.20.1
      modules:
        - cmake/3.20.1

  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr

  git:
    externals:
    - spec: git@2.18.0+tcltk
      prefix: /usr

  git-lfs:
    externals:
    - spec: git-lfs@2.10.0
      prefix: /usr

  all:
    compiler:: [intel@2021.3.0]
    providers:
    mpi:: [intel-oneapi-mpi@2021.3.0]
