# This template contains packages to be built with GCC that do *not* serve as link dependencies.
# They are either standalone applications (ecflow, awscli) and/or build dependencies (cmake, gmake) used by the nco-sci environments.
spack:
  concretizer:
    unify: when_possible

  config:
    install_tree:
      root: $env/install
    deprecated: true

  view: false

  include: []

  specs:
  - awscli
  - cmake@3
  - crtm-fix@=3.1.2.0 # must match crtm version in nco-sci
  - crtm-fix@=2.4.0.1_emc # must match crtm version in nco-sci
  - ecflow
  - git
  - git-lfs
  - gmake
  - imagemagick
  - perl
  - rsync
  - subversion
  # GEMPAK dependencies:
  - motif
  - libxt
  - libsm
  - libxtst
  - libice
  - libxi
  - libxext
  - libx11
  - xproto
