name: gcc-build
on: [push]

# Use custom shell with -l so .bash_profile is sourced which loads intel/oneapi/setvars.sh
# without having to do it in manually every step
defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  gcc-build:
    runs-on: ubuntu-latest
    name: gcc-build

    steps:

      - name: checkout
      - uses: actions/checkout@v2


      - name: setup
      - run: |
          cd spack-stack
          source setup.sh
          spack external find
          spack compiler find

          ls ~/.spack
          cat ~/.spack/linux/compilers.yaml
          cat ~/.spack/packages.yaml
          
