name: macos-clang-build
on: [push]

# Use custom shell with -l so .bash_profile is sourced
defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  build:
    strategy:
      matrix:
        app: [jedi-ufs, jedi-fv3, ufs-weather-model, nceplibs]
    runs-on: macos-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: install-env
        uses: ./.github/actions/setup-spack-stack
        with:
          app: ${{ matrix.app }}
          compiler: apple-clang
          mpi: mpich
          path: ${{ github.workspace }}
