name: util-tests

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ os_matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: checkout
        uses: actions/checkout
        with:
          submodules: false

      - name: run-util-tests
        run: |
          export SPACK_STACK_DIR=$PWD
          cd util/
          ./util_tests.sh
